// Generates src/filesystem/codepages.ts from glibc's iconv, which the C++ library converts SGOLD
// names with: for each codepage, the code point of every byte, or -1 where iconv rejects the byte.
//
//   gcc -O2 scripts/gen-codepages.c -o gen-codepages && ./gen-codepages > src/filesystem/codepages.ts
//
// Only stateless single-byte codepages that encode exactly what they decode are emitted. glibc's
// CP1255 and CP1258 compose combining marks, so they are not tables and are left out.

#include <iconv.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

static const char *CODEPAGES[] = {
    "CP1250", "CP1251", "CP1252", "CP1253", "CP1254", "CP1256", "CP1257", "CP874",
    "ISO-8859-1", "ISO-8859-2", "ISO-8859-3", "ISO-8859-4", "ISO-8859-5", "ISO-8859-6",
    "ISO-8859-7", "ISO-8859-8", "ISO-8859-9", "ISO-8859-10", "ISO-8859-11", "ISO-8859-13",
    "ISO-8859-14", "ISO-8859-15", "ISO-8859-16", "KOI8-R", "KOI8-U",
    "CP437", "CP850", "CP852", "CP855", "CP857", "CP866", "ANSI_X3.4-1968",
};

// Other names of the codepages above, each emitted only if iconv takes it: canonical name, alias
static const char *ALIASES[][2] = {
    { "CP1250", "WINDOWS-1250" }, { "CP1250", "MS-EE" },
    { "CP1251", "WINDOWS-1251" }, { "CP1251", "MS-CYRL" },
    { "CP1252", "WINDOWS-1252" }, { "CP1252", "MS-ANSI" },
    { "CP1253", "WINDOWS-1253" }, { "CP1253", "MS-GREEK" },
    { "CP1254", "WINDOWS-1254" }, { "CP1254", "MS-TURK" },
    { "CP1256", "WINDOWS-1256" }, { "CP1256", "MS-ARAB" },
    { "CP1257", "WINDOWS-1257" }, { "CP1257", "WINBALTRIM" },
    { "CP874", "WINDOWS-874" },
    { "ISO-8859-1", "LATIN1" }, { "ISO-8859-1", "L1" },
    { "ISO-8859-2", "LATIN2" }, { "ISO-8859-2", "L2" },
    { "ISO-8859-3", "LATIN3" }, { "ISO-8859-3", "L3" },
    { "ISO-8859-4", "LATIN4" }, { "ISO-8859-4", "L4" },
    { "ISO-8859-5", "CYRILLIC" },
    { "ISO-8859-6", "ARABIC" },
    { "ISO-8859-7", "GREEK" },
    { "ISO-8859-8", "HEBREW" },
    { "ISO-8859-9", "LATIN5" }, { "ISO-8859-9", "L5" },
    { "ISO-8859-10", "LATIN6" }, { "ISO-8859-10", "L6" },
    { "ISO-8859-13", "LATIN7" }, { "ISO-8859-13", "L7" },
    { "ISO-8859-14", "LATIN8" }, { "ISO-8859-14", "L8" },
    { "ISO-8859-15", "LATIN-9" }, { "ISO-8859-15", "LATIN9" },
    { "ISO-8859-16", "LATIN10" }, { "ISO-8859-16", "L10" },
    { "KOI8-R", "KOI8R" },
    { "CP437", "IBM437" }, { "CP437", "437" },
    { "CP850", "IBM850" }, { "CP850", "850" },
    { "CP852", "IBM852" }, { "CP852", "852" },
    { "CP855", "IBM855" }, { "CP855", "855" },
    { "CP857", "IBM857" }, { "CP857", "857" },
    { "CP866", "IBM866" }, { "CP866", "866" },
    { "ANSI_X3.4-1968", "ASCII" }, { "ANSI_X3.4-1968", "US-ASCII" },
};

// ISO-8859-<n> is also ISO8859-<n>, ISO_8859-<n> and ISO8859<n>
static const char *ISO_SPELLINGS[] = { "ISO8859-", "ISO_8859-", "ISO8859" };

static int accepted(const char *name) {
    iconv_t to = iconv_open(name, "UTF-8"), from = iconv_open("UTF-8", name);
    int     ok = to != (iconv_t)-1 && from != (iconv_t)-1;

    if (to != (iconv_t)-1) iconv_close(to);
    if (from != (iconv_t)-1) iconv_close(from);

    return ok;
}

static int decode_byte(const char *codepage, unsigned char byte, uint32_t *code_point) {
    iconv_t cd = iconv_open("UTF-32LE", codepage);
    char    in[1] = { (char)byte };
    char    out[16];
    char   *in_ptr = in, *out_ptr = out;
    size_t  in_left = 1, out_left = sizeof(out);
    size_t  result = iconv(cd, &in_ptr, &in_left, &out_ptr, &out_left);

    iconv_close(cd);

    if (result != 0 || in_left != 0 || sizeof(out) - out_left != 4) {
        return 0;
    }

    memcpy(code_point, out, 4);

    return 1;
}

static int encode_code_point(iconv_t cd, uint32_t code_point, unsigned char *byte) {
    char    in[4];
    char    out[16];
    char   *in_ptr = in, *out_ptr = out;
    size_t  in_left = 4, out_left = sizeof(out);

    memcpy(in, &code_point, 4);
    iconv(cd, NULL, NULL, NULL, NULL);

    if (iconv(cd, &in_ptr, &in_left, &out_ptr, &out_left) != 0 || in_left != 0 || sizeof(out) - out_left != 1) {
        return 0;
    }

    *byte = (unsigned char)out[0];

    return 1;
}

int main(void) {
    printf("// Generated by scripts/gen-codepages.c from glibc's iconv. Do not edit.\n");
    printf("//\n");
    printf("// The code point of every byte of the codepage, or -1 where iconv rejects the byte.\n\n");
    printf("export const CODEPAGE_TABLES: Record<string, readonly number[]> = {\n");

    for (size_t i = 0; i < sizeof(CODEPAGES) / sizeof(CODEPAGES[0]); ++i) {
        const char *codepage = CODEPAGES[i];
        uint32_t    table[256];
        int         valid[256];

        for (int byte = 0; byte < 256; ++byte) {
            valid[byte] = decode_byte(codepage, (unsigned char)byte, &table[byte]);
        }

        iconv_t cd = iconv_open(codepage, "UTF-32LE");

        for (uint32_t code_point = 1; code_point < 0x110000; ++code_point) {
            unsigned char byte;

            if (code_point >= 0xD800 && code_point <= 0xDFFF) {
                continue;
            }

            if (encode_code_point(cd, code_point, &byte) && !(valid[byte] && table[byte] == code_point)) {
                fprintf(stderr, "%s encodes U+%04X to %02X, which does not decode back\n", codepage, code_point, byte);

                return 1;
            }
        }

        iconv_close(cd);

        printf("    \"%s\": [", codepage);

        for (int byte = 0; byte < 256; ++byte) {
            printf("%s%s%d", byte ? "," : "", byte % 16 ? "" : "\n        ", valid[byte] ? (int)table[byte] : -1);
        }

        printf(",\n    ],\n");
    }

    printf("};\n\n");
    printf("// Other names iconv takes for them\n");
    printf("export const CODEPAGE_ALIASES: Record<string, string> = {\n");

    for (size_t i = 0; i < sizeof(ALIASES) / sizeof(ALIASES[0]); ++i) {
        if (accepted(ALIASES[i][1])) {
            printf("    \"%s\": \"%s\",\n", ALIASES[i][1], ALIASES[i][0]);
        }
    }

    for (int n = 1; n <= 16; ++n) {
        char canonical[32];

        snprintf(canonical, sizeof(canonical), "ISO-8859-%d", n);

        if (n == 12 || !accepted(canonical)) {
            continue;
        }

        for (size_t i = 0; i < sizeof(ISO_SPELLINGS) / sizeof(ISO_SPELLINGS[0]); ++i) {
            char alias[32];

            snprintf(alias, sizeof(alias), "%s%d", ISO_SPELLINGS[i], n);

            if (accepted(alias)) {
                printf("    \"%s\": \"%s\",\n", alias, canonical);
            }
        }
    }

    printf("};\n");

    return 0;
}
